"""
Digital PRF model — Stores completed digital Patient Report Forms.
Each PRF is linked to a provider, vehicle, and crew members.
Real-time timestamps are captured when crew taps buttons.
Auto-sequential PRF numbers are generated by the system.
"""
import uuid
import enum
from datetime import datetime, timezone
from decimal import Decimal
from sqlalchemy import String, Text, ForeignKey, DateTime, JSON, Enum as SAEnum, Integer, Numeric
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database import Base


class PRFStatus(str, enum.Enum):
    DRAFT = "draft"
    SUBMITTED = "submitted"
    PROCESSED = "processed"
    FAILED = "failed"
    CORRECTED = "corrected"


class DigitalPRF(Base):
    __tablename__ = "digital_prfs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    # ── Provider / Vehicle / Crew ─────────────────────────
    provider_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("service_providers.id"), nullable=False
    )
    vehicle_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("vehicles.id"), nullable=True
    )
    crew_member_1_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("crew_members.id"), nullable=True
    )
    crew_member_2_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("crew_members.id"), nullable=True
    )

    # ── PRF Identification ────────────────────────────────
    prf_number: Mapped[int] = mapped_column(
        Integer, unique=True, nullable=False, index=True,
        comment="Auto-sequential PRF number"
    )
    case_number: Mapped[str | None] = mapped_column(
        String(50), unique=True, nullable=True,
        comment="Auto-generated case number e.g. JEMS-2026-04-001730"
    )

    # ── Status ────────────────────────────────────────────
    status: Mapped[PRFStatus] = mapped_column(
        SAEnum(PRFStatus, name="prf_status"),
        nullable=False, default=PRFStatus.DRAFT,
    )

    # ── Form Data (all ~120 fields as structured JSON) ────
    form_data: Mapped[dict | None] = mapped_column(
        JSON, nullable=True, default=dict,
        comment="Full PRF content — patient, clinical, vitals, etc."
    )

    # ── Real-time Timestamps ──────────────────────────────
    # Captured when crew taps "Mark" buttons — not manually typed
    time_call_received: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    time_dispatched: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    time_mobile: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    time_on_scene: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    time_depart_scene: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    time_at_destination: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    time_handover: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    time_available: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    time_back_to_base: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # ── Odometer readings (manual entry by crew) ──────────
    km_call_received: Mapped[Decimal | None] = mapped_column(Numeric(8, 1), nullable=True)
    km_dispatched: Mapped[Decimal | None] = mapped_column(Numeric(8, 1), nullable=True)
    km_mobile: Mapped[Decimal | None] = mapped_column(Numeric(8, 1), nullable=True)
    km_on_scene: Mapped[Decimal | None] = mapped_column(Numeric(8, 1), nullable=True)
    km_depart_scene: Mapped[Decimal | None] = mapped_column(Numeric(8, 1), nullable=True)
    km_at_destination: Mapped[Decimal | None] = mapped_column(Numeric(8, 1), nullable=True)
    km_handover: Mapped[Decimal | None] = mapped_column(Numeric(8, 1), nullable=True)
    km_available: Mapped[Decimal | None] = mapped_column(Numeric(8, 1), nullable=True)
    km_back_to_base: Mapped[Decimal | None] = mapped_column(Numeric(8, 1), nullable=True)

    # ── Geo-location captures keyed by timestamp field ────
    # Shape: { "time_dispatched": {"lat": -26.1, "lng": 28.0, "accuracy_m": 12, "captured_at": "..."}, ... }
    # Crew confirms each capture in-app before it's saved.
    geo_locations: Mapped[dict | None] = mapped_column(
        JSONB, nullable=True, default=dict,
        comment="GPS coordinates captured when crew marks each timestamp",
    )

    # ── Review flags (machine/human-generated billing review flags) ──
    review_flags: Mapped[list] = mapped_column(
        JSONB, nullable=False, default=list,
        comment="Review flags for billing validation",
    )

    # ── Billing linkage ───────────────────────────────────
    billing_schema_code: Mapped[str | None] = mapped_column(
        String(50), nullable=True, index=True,
        comment="Links this PRF to a rate_schemas.schema_code for billing",
    )

    # ── Signatures (base64 PNG from touch canvas) ─────────
    patient_signature: Mapped[str | None] = mapped_column(Text, nullable=True)
    witness_signature: Mapped[str | None] = mapped_column(Text, nullable=True)
    handover_signature: Mapped[str | None] = mapped_column(Text, nullable=True)
    crew_signature: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Pipeline linkage ──────────────────────────────────
    case_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("cases.id"), nullable=True,
        comment="Set when processed into the billing pipeline"
    )
    document_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("documents.id"), nullable=True,
    )
    correction_of_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("digital_prfs.id"), nullable=True,
        comment="Links this row to the original failed PRF it corrects. NULL if not a correction.",
    )

    # ── Timestamps ────────────────────────────────────────
    submitted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # ── Processing / failure tracking ─────────────────────
    processing_error: Mapped[str | None] = mapped_column(
        Text, nullable=True,
        comment="Error message from failed billing pipeline",
    )
    processing_attempts: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0,
        comment="Number of Celery processing attempts",
    )
    last_processing_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True,
        comment="Timestamp of last processing attempt",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # ── Relationships ─────────────────────────────────────
    provider = relationship("ServiceProvider", back_populates="digital_prfs")
    vehicle = relationship("Vehicle")
    crew_member_1 = relationship("CrewMember", foreign_keys=[crew_member_1_id])
    crew_member_2 = relationship("CrewMember", foreign_keys=[crew_member_2_id])

    def __repr__(self):
        return f"<DigitalPRF #{self.prf_number} ({self.status.value})>"
