"""
Digital PRF model — Stores completed digital Patient Report Forms.
Each PRF is linked to a provider, vehicle, and crew members.
Real-time timestamps are captured when crew taps buttons.
Auto-sequential PRF numbers are generated by the system.
"""
from typing import Union
import uuid
import enum
from datetime import datetime, timezone
from decimal import Decimal
from sqlalchemy import String, Text, ForeignKey, DateTime, JSON, Enum as SAEnum, Integer, Numeric, UniqueConstraint, Index
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database import Base
from app.utils.encrypted_types import FormDataWithEncryptedPatientID


class PRFStatus(str, enum.Enum):
    DRAFT = "draft"
    SUBMITTED = "submitted"
    PROCESSED = "processed"
    FAILED = "failed"
    CORRECTED = "corrected"


class DigitalPRF(Base):
    __tablename__ = "digital_prfs"

    # PRF numbers count independently per provider, so #1 can exist for every
    # company. Uniqueness is therefore scoped to (provider_id, prf_number) — a
    # global unique on prf_number alone would force one shared counter.
    # These two indexes exist ONLY as raw op.execute() statements in migrations
    # (b4c8d2e6f7a3 and a3b7c9d1e5f2), so they were invisible to the ORM. Any
    # database built from the models rather than from the migration chain — which
    # is how a brand-new install is created, see backend/bootstrap_schema.py —
    # came up without them. Both back queries that run on every page load of the
    # failed-PRF queue, over a table that keeps seven years of records.
    # Names match the migrations exactly, so existing databases already satisfy
    # them and nothing is created twice.
    __table_args__ = (
        UniqueConstraint("provider_id", "prf_number", name="uq_digital_prf_provider_number"),
        Index("ix_digital_prfs_status", "status"),
        Index("ix_digital_prfs_review_flags", "review_flags", postgresql_using="gin"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    # ── Provider / Vehicle / Crew ─────────────────────────
    provider_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("service_providers.id"), nullable=False,
        index=True,  # provider dashboard filters every query by provider_id;
                     # indexed so listing/searching stays fast across 7 years of PRFs
    )
    vehicle_id: Mapped[Union[uuid.UUID, None]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("vehicles.id"), nullable=True
    )
    crew_member_1_id: Mapped[Union[uuid.UUID, None]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("crew_members.id"), nullable=True
    )
    crew_member_2_id: Mapped[Union[uuid.UUID, None]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("crew_members.id"), nullable=True
    )

    # ── PRF Identification ────────────────────────────────
    prf_number: Mapped[int] = mapped_column(
        Integer, nullable=False, index=True,
        comment="Per-provider sequential PRF number (unique within provider_id)"
    )
    case_number: Mapped[Union[str, None]] = mapped_column(
        String(50), unique=True, nullable=True,
        comment="Auto-generated case number e.g. JEMS-2026-04-001730"
    )

    # ── Status ────────────────────────────────────────────
    status: Mapped[PRFStatus] = mapped_column(
        SAEnum(PRFStatus, name="prf_status"),
        nullable=False, default=PRFStatus.DRAFT,
    )

    # ── Form Data (all ~120 fields as structured JSON) ────
    form_data: Mapped[Union[dict, None]] = mapped_column(
        # The SA ID number inside this blob is encrypted at rest; every other
        # key is stored as-is. See app/utils/encrypted_types.py for why only
        # that one field, and what it costs (raw-SQL scans of the ID stop
        # matching, which is the point).
        FormDataWithEncryptedPatientID, nullable=True, default=dict,
        comment="Full PRF content — patient, clinical, vitals. patient_id_number encrypted."
    )
    patient_id_hash: Mapped[Union[str, None]] = mapped_column(
        # Derived from form_data['patient_id_number'] on every write.
        #
        # Encrypting the ID broke searching for a patient by it: the provider
        # PRF search runs `cast(form_data AS text) ILIKE`, which now sees
        # ciphertext and silently matches nothing. This restores the capability
        # AND makes it fast — an indexed equality lookup instead of detoasting
        # and scanning every 58KB clinical blob.
        String(64), nullable=True, index=True,
        comment="HMAC-SHA256 lookup hash of form_data['patient_id_number']"
    )

    # ── Real-time Timestamps ──────────────────────────────
    # Captured when crew taps "Mark" buttons — not manually typed
    time_call_received: Mapped[Union[datetime, None]] = mapped_column(DateTime(timezone=True), nullable=True)
    time_dispatched: Mapped[Union[datetime, None]] = mapped_column(DateTime(timezone=True), nullable=True)
    time_mobile: Mapped[Union[datetime, None]] = mapped_column(DateTime(timezone=True), nullable=True)
    time_on_scene: Mapped[Union[datetime, None]] = mapped_column(DateTime(timezone=True), nullable=True)
    time_depart_scene: Mapped[Union[datetime, None]] = mapped_column(DateTime(timezone=True), nullable=True)
    time_at_destination: Mapped[Union[datetime, None]] = mapped_column(DateTime(timezone=True), nullable=True)
    time_handover: Mapped[Union[datetime, None]] = mapped_column(DateTime(timezone=True), nullable=True)
    time_available: Mapped[Union[datetime, None]] = mapped_column(DateTime(timezone=True), nullable=True)
    time_back_to_base: Mapped[Union[datetime, None]] = mapped_column(DateTime(timezone=True), nullable=True)

    # ── Odometer readings (manual entry by crew) ──────────
    km_call_received: Mapped[Union[Decimal, None]] = mapped_column(Numeric(8, 1), nullable=True)
    km_dispatched: Mapped[Union[Decimal, None]] = mapped_column(Numeric(8, 1), nullable=True)
    km_mobile: Mapped[Union[Decimal, None]] = mapped_column(Numeric(8, 1), nullable=True)
    km_on_scene: Mapped[Union[Decimal, None]] = mapped_column(Numeric(8, 1), nullable=True)
    km_depart_scene: Mapped[Union[Decimal, None]] = mapped_column(Numeric(8, 1), nullable=True)
    km_at_destination: Mapped[Union[Decimal, None]] = mapped_column(Numeric(8, 1), nullable=True)
    km_handover: Mapped[Union[Decimal, None]] = mapped_column(Numeric(8, 1), nullable=True)
    km_available: Mapped[Union[Decimal, None]] = mapped_column(Numeric(8, 1), nullable=True)
    km_back_to_base: Mapped[Union[Decimal, None]] = mapped_column(Numeric(8, 1), nullable=True)

    # ── Geo-location captures keyed by timestamp field ────
    # Shape: { "time_dispatched": {"lat": -26.1, "lng": 28.0, "accuracy_m": 12, "captured_at": "..."}, ... }
    # Crew confirms each capture in-app before it's saved.
    geo_locations: Mapped[Union[dict, None]] = mapped_column(
        JSONB, nullable=True, default=dict,
        comment="GPS coordinates captured when crew marks each timestamp",
    )

    # ── Review flags (machine/human-generated billing review flags) ──
    review_flags: Mapped[list] = mapped_column(
        JSONB, nullable=False, default=list,
        comment="Review flags for billing validation",
    )

    # ── Billing linkage ───────────────────────────────────
    billing_schema_code: Mapped[Union[str, None]] = mapped_column(
        String(50), nullable=True, index=True,
        comment="Links this PRF to a rate_schemas.schema_code for billing",
    )

    # ── Signatures (base64 PNG from touch canvas) ─────────
    patient_signature: Mapped[Union[str, None]] = mapped_column(Text, nullable=True)
    witness_signature: Mapped[Union[str, None]] = mapped_column(Text, nullable=True)
    handover_signature: Mapped[Union[str, None]] = mapped_column(Text, nullable=True)
    crew_signature: Mapped[Union[str, None]] = mapped_column(Text, nullable=True)
    valuables_signature: Mapped[Union[str, None]] = mapped_column(Text, nullable=True)

    # ── Pipeline linkage ──────────────────────────────────
    case_id: Mapped[Union[uuid.UUID, None]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("cases.id"), nullable=True, index=True,
        comment="Set when processed into the billing pipeline"
        # Indexed: every /api/cases list, get and patch joins on this to attach
        # the PRF. Unindexed it was a sequential scan of digital_prfs on each
        # call — measured 1021ms vs 1.4ms on a 3M-row table.
    )
    document_id: Mapped[Union[uuid.UUID, None]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("documents.id"), nullable=True,
    )
    correction_of_id: Mapped[Union[uuid.UUID, None]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("digital_prfs.id"), nullable=True, index=True,
        comment="Links this row to the original failed PRF it corrects. NULL if not a correction.",
        # Indexed: _next_prf_number filters on `correction_of_id IS NULL` for
        # EVERY PRF creation. The index existed only as raw SQL inside migration
        # d6e7f8a9b0c1, so a fresh bootstrap_schema.py install had no such index
        # at all — declaring it here is what makes the two paths agree.
    )

    # ── Timestamps ────────────────────────────────────────
    submitted_at: Mapped[Union[datetime, None]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # ── Receiving-facility email (post-submit PDF send) ───
    facility_email_sent_to: Mapped[Union[str, None]] = mapped_column(
        String(255), nullable=True,
        comment="Recipient the PRF PDF was emailed to (audit + duplicate-send guard)",
    )
    facility_email_sent_at: Mapped[Union[datetime, None]] = mapped_column(
        DateTime(timezone=True), nullable=True,
        comment="When the PRF PDF was emailed to the receiving facility",
    )
    facility_email_error: Mapped[Union[str, None]] = mapped_column(
        String(50), nullable=True,
        comment="Terminal failure reason from the last facility-email attempt (e.g. smtp_auth_failed); cleared on re-queue and on success",
    )

    # ── Processing / failure tracking ─────────────────────
    processing_error: Mapped[Union[str, None]] = mapped_column(
        Text, nullable=True,
        comment="Error message from failed billing pipeline",
    )
    processing_attempts: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0,
        comment="Number of Celery processing attempts",
    )
    last_processing_at: Mapped[Union[datetime, None]] = mapped_column(
        DateTime(timezone=True), nullable=True,
        comment="Timestamp of last processing attempt",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # ── Relationships ─────────────────────────────────────
    provider = relationship("ServiceProvider", back_populates="digital_prfs")
    vehicle = relationship("Vehicle")
    crew_member_1 = relationship("CrewMember", foreign_keys=[crew_member_1_id])
    crew_member_2 = relationship("CrewMember", foreign_keys=[crew_member_2_id])

    def __repr__(self):
        return f"<DigitalPRF #{self.prf_number} ({self.status.value})>"


# Keep patient_id_hash in step with the encrypted ID inside form_data.
#
# Registered at import so the API, the Celery workers, the backfill and the
# tests all behave identically — a PRF written by a worker without a hash is a
# PRF the office cannot find.
from sqlalchemy import event as _event  # noqa: E402

from app.utils.patient_id import id_hash as _id_hash  # noqa: E402


def _sync_prf_patient_id_hash(mapper, connection, target):  # noqa: ARG001
    fd = target.form_data if isinstance(target.form_data, dict) else {}
    raw = fd.get("patient_id_number")
    # Always recomputed rather than gated on change detection: form_data is
    # plain JSON, so an in-place mutation leaves no history for SQLAlchemy to
    # report, and a stale hash points at the wrong patient. An HMAC is cheap.
    target.patient_id_hash = _id_hash(str(raw)) if raw not in (None, "") else None


_event.listen(DigitalPRF, "before_insert", _sync_prf_patient_id_hash)
_event.listen(DigitalPRF, "before_update", _sync_prf_patient_id_hash)

