#!/usr/bin/env python
"""
Create the database schema on a BRAND-NEW instance, then stamp Alembic at head.

WHY THIS EXISTS
---------------
`alembic upgrade head` cannot build this schema from nothing. The initial
revision (04be48895f1c) was autogenerated against an already-populated database
and committed with an empty `upgrade()` body — it is literally `pass`. Every
revision after it ALTERs tables that the chain never creates, so on an empty
database `alembic upgrade head` either creates nothing at all or dies on the
first ALTER. Existing installs never noticed: their tables were made by
SQLAlchemy's create_all() long before Alembic was introduced, and the version
table was stamped by hand afterwards.

That is invisible until the day the product is installed somewhere new — which
is exactly what handing it to a client to run on their own VM means.

WHAT THIS DOES
--------------
  empty database        -> create every table from the ORM models, then stamp
                           the Alembic version table at head, so all future
                           releases upgrade normally with `alembic upgrade head`.
  already bootstrapped  -> refuse, and tell you to run `alembic upgrade head`.
  tables but no stamp   -> refuse. That state is ambiguous (a half-finished
                           bootstrap, or a legacy create_all database) and
                           guessing risks writing over real patient data.

It never DROPs, never TRUNCATEs and never touches a row.

USAGE
-----
    cd backend
    python bootstrap_schema.py                 # report what it would do
    python bootstrap_schema.py --apply         # do it

DATABASE_URL is read from the environment (or backend/.env), the same way the
application reads it.
"""
from __future__ import annotations

import argparse
import asyncio
import os
import re
import sys

# Import the app package the same way the application does.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:  # pragma: no cover - dotenv is in requirements
    pass


def _redact(url: str) -> str:
    """Strip credentials before anything is printed or logged."""
    return re.sub(r"//[^/@]*@", "//***:***@", url or "")


ALEMBIC_INI = os.path.join(os.path.dirname(os.path.abspath(__file__)), "alembic.ini")


async def _inspect(engine):
    """Return (table_names, alembic_version or None)."""
    from sqlalchemy import inspect as sa_inspect, text

    async with engine.connect() as conn:
        tables = await conn.run_sync(lambda sync_conn: sa_inspect(sync_conn).get_table_names())

        version = None
        if "alembic_version" in tables:
            result = await conn.execute(text("SELECT version_num FROM alembic_version"))
            row = result.first()
            version = row[0] if row else None

    return set(tables), version


def _alembic_head() -> str:
    from alembic.config import Config
    from alembic.script import ScriptDirectory

    cfg = Config(ALEMBIC_INI)
    script = ScriptDirectory.from_config(cfg)
    heads = script.get_heads()
    if len(heads) != 1:
        raise SystemExit(
            f"ERROR: the migration tree has {len(heads)} heads {heads}. "
            f"Merge them before bootstrapping."
        )
    return heads[0]


async def _create_schema(url: str, apply: bool, head: str) -> int:
    """Async half: inspect the database and, if it is empty, create the tables.

    Returns 0 to mean "carry on and stamp", 10 to mean "finished, nothing more
    to do", and anything else is a failure.
    """
    from sqlalchemy.ext.asyncio import create_async_engine
    from app.database import Base

    engine = create_async_engine(url, echo=False)
    try:
        tables, version = await _inspect(engine)
        # alembic_version is bookkeeping, not schema.
        real_tables = tables - {"alembic_version"}

        if version:
            print(f"REFUSING: this database is already stamped at Alembic revision {version}.")
            print("          Nothing to bootstrap. To apply pending migrations run:")
            print("              alembic upgrade head")
            return 1

        if real_tables:
            print(f"REFUSING: the database already contains {len(real_tables)} tables but has no")
            print("          Alembic stamp. That is ambiguous — it could be a legacy")
            print("          create_all() database or a half-finished bootstrap, and this")
            print("          script will not guess with real data present.")
            print()
            print("          If you are certain the schema is current, stamp it by hand:")
            print(f"              alembic stamp {head}")
            print("          Sample of existing tables: " + ", ".join(sorted(real_tables)[:8]))
            return 1

        print("Database is EMPTY — safe to bootstrap.")
        if not apply:
            print()
            print("DRY RUN. Would create every table from the ORM models, then stamp")
            print(f"the schema at Alembic revision {head}.")
            print("Re-run with --apply to do it.")
            return 10

        print("Creating tables from the ORM models...")
        async with engine.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)

        created, _ = await _inspect(engine)
        created -= {"alembic_version"}
        print(f"Created {len(created)} tables.")

        # Verify before stamping: a stamp on an incomplete schema is worse than
        # no stamp, because every future `alembic upgrade head` would skip the
        # migrations that would have repaired it.
        expected = set(Base.metadata.tables.keys())
        missing = expected - created
        if missing:
            print(f"ERROR: {len(missing)} expected tables were not created: "
                  f"{', '.join(sorted(missing)[:10])}", file=sys.stderr)
            print("Not stamping. Fix the error and re-run.", file=sys.stderr)
            return 3

        return 0
    finally:
        await engine.dispose()


def main(apply: bool) -> int:
    # Import for the side effect of registering every model on Base.metadata.
    from app.database import Base
    import app.models  # noqa: F401

    url = os.getenv("DATABASE_URL")
    if not url:
        print("ERROR: DATABASE_URL is not set.", file=sys.stderr)
        return 2

    head = _alembic_head()

    print(f"Database : {_redact(url)}")
    print(f"Alembic head : {head}")
    print(f"Models declare {len(Base.metadata.tables)} tables.")
    print()

    rc = asyncio.run(_create_schema(url, apply, head))
    if rc == 10:      # dry run finished cleanly
        return 0
    if rc != 0:
        return rc

    # The stamp MUST run outside the event loop above. alembic/env.py calls
    # asyncio.run() itself, so invoking command.stamp() from inside a coroutine
    # dies with "asyncio.run() cannot be called from a running event loop" —
    # which previously left the tables created but UNSTAMPED, exactly the
    # ambiguous state this script refuses to touch on a re-run.
    print(f"Stamping Alembic at {head}...")
    from alembic import command
    from alembic.config import Config

    cfg = Config(ALEMBIC_INI)
    cfg.set_main_option("sqlalchemy.url", url)
    command.stamp(cfg, head)

    print()
    print("DONE. The schema is current and Alembic is stamped at head.")
    print("From here on, apply new releases with: alembic upgrade head")
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--apply",
        action="store_true",
        help="actually create the schema (without this it only reports)",
    )
    args = parser.parse_args()
    raise SystemExit(main(args.apply))
