"""Initial schema

Revision ID: 04be48895f1c
Revises: 
Create Date: 2026-03-27 16:52:43.688676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04be48895f1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    THIS REVISION CREATES NOTHING — and that is not an oversight to "fix" by
    pasting a schema in here.

    It was autogenerated against a database whose tables already existed (they
    were made by SQLAlchemy's create_all()), so Alembic correctly saw no
    difference and emitted an empty body. Every later revision therefore ALTERs
    tables that this chain never creates.

    The consequence: `alembic upgrade head` CANNOT build this schema from an
    empty database. A brand-new install must be bootstrapped first:

        cd backend
        python bootstrap_schema.py --apply

    which creates the tables from the ORM models and stamps the version table at
    head. After that, `alembic upgrade head` is the normal upgrade path forever.

    This body stays empty so that existing databases — already stamped past this
    revision — are unaffected.
    """
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
