"""Add valuables_signature

Revision ID: 283026c60d1d
Revises: 6a03f645e262
Create Date: 2026-07-02 10:29:03.466242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '283026c60d1d'
down_revision: Union[str, Sequence[str], None] = '6a03f645e262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_prfs', sa.Column('valuables_signature', sa.Text(), nullable=True))
    op.alter_column('service_providers', 'portal_login_email',
               existing_type=sa.VARCHAR(length=255),
               comment="Email used on main EMSMCA login page to redirect to this provider's portal",
               existing_nullable=True)
    # Dev DBs have a UNIQUE constraint here; prod (migrated via d7e8f9a0b1c2) has a
    # unique index instead. Use IF EXISTS / IF NOT EXISTS so both states converge.
    op.execute('ALTER TABLE service_providers DROP CONSTRAINT IF EXISTS service_providers_portal_login_email_key')
    op.execute('CREATE UNIQUE INDEX IF NOT EXISTS ix_service_providers_portal_login_email ON service_providers (portal_login_email)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_providers_portal_login_email'), table_name='service_providers')
    op.create_unique_constraint(op.f('service_providers_portal_login_email_key'), 'service_providers', ['portal_login_email'], postgresql_nulls_not_distinct=False)
    op.alter_column('service_providers', 'portal_login_email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Email used on main EMSMCA login page to redirect to this provider's portal",
               existing_nullable=True)
    op.drop_column('digital_prfs', 'valuables_signature')
    # ### end Alembic commands ###
