"""add_contact_email_phone_to_scheme_configs

Revision ID: 2e5ea3606413
Revises: a1b2c3d4e5f6
Create Date: 2026-04-18 09:24:48.900297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e5ea3606413'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'dispatch_type',
               existing_type=sa.VARCHAR(length=20),
               comment="Canonical call type — 'Primary' or 'IFT'. Normalised from extracted_data['incident_type'] via normalise_call_type(). Legacy 'IHT' rows are migrated to 'IFT' by Alembic.",
               existing_comment='Primary, IHT (Inter-Hospital Transfer)',
               existing_nullable=True)
    op.alter_column('cases', 'referring_doctor_pr',
               existing_type=sa.VARCHAR(length=20),
               comment='Referring doctor PR number — mandatory for IFT (Inter-Facility Transfer)',
               existing_comment='Referring doctor PR number — mandatory for IHT',
               existing_nullable=True)
    op.alter_column('claims', 'dispatch_reference_number',
               existing_type=sa.VARCHAR(length=100),
               comment='CAD/Dispatch reference — used when billing an AGGREGATOR payer (e.g. ER24, Netcare 911)',
               existing_nullable=True)
    op.alter_column('documents', 'group_id',
               existing_type=sa.VARCHAR(length=36),
               comment='UUID shared by documents in the same bundle',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('documents', 'is_group_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='True if this is the primary PRF in a bundle',
               existing_server_default=sa.text('false'))
    op.drop_index('idx_documents_group_id', table_name='documents')
    op.create_index(op.f('ix_documents_group_id'), 'documents', ['group_id'], unique=False)
    op.add_column('scheme_configs', sa.Column('contact_email', sa.String(length=255), nullable=True, comment='Scheme auth department email for manual email fallback'))
    op.add_column('scheme_configs', sa.Column('phone_number', sa.String(length=50), nullable=True, comment='Scheme contact phone number'))
    op.alter_column('scheme_configs', 'payer_type',
               existing_type=sa.VARCHAR(length=20),
               comment='SCHEME (e.g. Discovery, GEMS) or AGGREGATOR (e.g. ER24, Netcare 911)',
               existing_nullable=False,
               existing_server_default=sa.text("'SCHEME'::character varying"))
    op.drop_index('idx_scheme_rules_active', table_name='scheme_rules')
    op.drop_index('idx_scheme_rules_priority', table_name='scheme_rules')
    op.drop_index('idx_scheme_rules_scheme', table_name='scheme_rules')
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Consecutive failed login attempts',
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'locked_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Account locked until this timestamp (NULL = not locked)',
               existing_nullable=True)
    op.alter_column('users', 'password_changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last password change timestamp',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last password change timestamp',
               existing_nullable=True)
    op.alter_column('users', 'locked_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Account locked until this timestamp (NULL = not locked)',
               existing_nullable=True)
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='Consecutive failed login attempts',
               existing_server_default=sa.text('0'))
    op.create_index('idx_scheme_rules_scheme', 'scheme_rules', ['scheme_name'], unique=False)
    op.create_index('idx_scheme_rules_priority', 'scheme_rules', ['priority', 'created_at'], unique=False)
    op.create_index('idx_scheme_rules_active', 'scheme_rules', ['is_active'], unique=False)
    op.alter_column('scheme_configs', 'payer_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='SCHEME (e.g. Discovery, GEMS) or AGGREGATOR (e.g. ER24, Netcare 911)',
               existing_nullable=False,
               existing_server_default=sa.text("'SCHEME'::character varying"))
    op.drop_column('scheme_configs', 'phone_number')
    op.drop_column('scheme_configs', 'contact_email')
    op.drop_index(op.f('ix_documents_group_id'), table_name='documents')
    op.create_index('idx_documents_group_id', 'documents', ['group_id'], unique=False)
    op.alter_column('documents', 'is_group_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='True if this is the primary PRF in a bundle',
               existing_server_default=sa.text('false'))
    op.alter_column('documents', 'group_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='UUID shared by documents in the same bundle',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('claims', 'dispatch_reference_number',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='CAD/Dispatch reference — used when billing an AGGREGATOR payer (e.g. ER24, Netcare 911)',
               existing_nullable=True)
    op.alter_column('cases', 'referring_doctor_pr',
               existing_type=sa.VARCHAR(length=20),
               comment='Referring doctor PR number — mandatory for IHT',
               existing_comment='Referring doctor PR number — mandatory for IFT (Inter-Facility Transfer)',
               existing_nullable=True)
    op.alter_column('cases', 'dispatch_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Primary, IHT (Inter-Hospital Transfer)',
               existing_comment="Canonical call type — 'Primary' or 'IFT'. Normalised from extracted_data['incident_type'] via normalise_call_type(). Legacy 'IHT' rows are migrated to 'IFT' by Alembic.",
               existing_nullable=True)
    # ### end Alembic commands ###
