"""add_scheme_adapter_fields

Revision ID: 66bd72a732f9
Revises: 3f98acd077f5
Create Date: 2026-03-30 19:00:25.176636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66bd72a732f9'
down_revision: Union[str, Sequence[str], None] = '3f98acd077f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'dependant_code',
               existing_type=sa.VARCHAR(length=5),
               comment='Scheme dependant code e.g. 00=principal, 01=spouse',
               existing_nullable=True)
    op.alter_column('cases', 'dispatch_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Primary, IHT (Inter-Hospital Transfer)',
               existing_nullable=True)
    op.alter_column('cases', 'referring_doctor_pr',
               existing_type=sa.VARCHAR(length=20),
               comment='Referring doctor PR number — mandatory for IHT',
               existing_nullable=True)
    op.alter_column('cases', 'auth_flag',
               existing_type=sa.BOOLEAN(),
               comment="True when scheme couldn't be matched — pins PRF to top of queue",
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('cases', 'auth_flag_reason',
               existing_type=sa.TEXT(),
               comment="Reason for flagging e.g. 'No API config found for scheme: XYZ Medical'",
               existing_nullable=True)
    op.alter_column('documents', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the HITL reviewer approved the data',
               existing_nullable=True)
    op.alter_column('documents', 'reviewed_by_id',
               existing_type=sa.UUID(),
               comment='User who performed the HITL review',
               existing_nullable=True)
    op.add_column('scheme_configs', sa.Column('integration_type', sa.String(length=50), nullable=False, comment='Adapter type: discovery, medscheme, generic, mock'))
    op.add_column('scheme_configs', sa.Column('api_key', sa.Text(), nullable=True, comment="Static API Key for schemes that don't use OAuth2"))
    op.add_column('scheme_configs', sa.Column('provider_practice_number', sa.String(length=50), nullable=True, comment='BHF Practice Number if required by scheme headers'))
    op.alter_column('users', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='List of page-keys the user can access',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of page-keys the user can access',
               existing_nullable=True)
    op.drop_column('scheme_configs', 'provider_practice_number')
    op.drop_column('scheme_configs', 'api_key')
    op.drop_column('scheme_configs', 'integration_type')
    op.alter_column('documents', 'reviewed_by_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who performed the HITL review',
               existing_nullable=True)
    op.alter_column('documents', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the HITL reviewer approved the data',
               existing_nullable=True)
    op.alter_column('cases', 'auth_flag_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Reason for flagging e.g. 'No API config found for scheme: XYZ Medical'",
               existing_nullable=True)
    op.alter_column('cases', 'auth_flag',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment="True when scheme couldn't be matched — pins PRF to top of queue",
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('cases', 'referring_doctor_pr',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Referring doctor PR number — mandatory for IHT',
               existing_nullable=True)
    op.alter_column('cases', 'dispatch_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Primary, IHT (Inter-Hospital Transfer)',
               existing_nullable=True)
    op.alter_column('cases', 'dependant_code',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='Scheme dependant code e.g. 00=principal, 01=spouse',
               existing_nullable=True)
    # ### end Alembic commands ###
